12544 next side choice
vassalengine/vassal pull request #12646
Opened 2023-09-04 13:51 UTC by riverwanderer

First effort at providing a hotseat over-ride.

If property _VassalNextSide_ is defined, that will be used.

2023-09-04 16:34 UTC, riverwanderer commented
Bug to fix (occurs when VassalNextSide is not defined): 
023-09-04 17:29:31,915 [14777-AWT-EventQueue-0] ERROR VASSAL.tools.ErrorDialog - 
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "nextChoice" is null
	at VASSAL.build.module.PlayerRoster.promptForSide(PlayerRoster.java:780)

Also, on second thoughts, it will not be sensible to set this property locally, as then any given module that uses the feature will not be able to provide a hotseat function that works for both solo and multiplayer modes.

2023-09-04 18:18 UTC, riverwanderer commented
Retested successfully with standard hotseat side-switching and with the VassalNextSide over-ride feature.
Vassal Reference Manual update to follow.

2023-09-12 20:31 UTC, Cattlesquat requested changes
I see some issues with expecting a translated string in a Global Property (see below)

2023-09-13 09:07 UTC, riverwanderer commented on vassal-doc/src/main/readme-referencemanual/ReferenceManual/GameModule.adoc
> +The Switch Sides component includes hot-seat support. If the Module <<GlobalProperties.adoc#top,Global Property>> _VassalNextSide_ is defined and set to an available side, that side will be offered.
Yes, VassalSkipSideList is a property from PR #12636. I've removed it from there whilst I re-think this PR (12646) and #12652.

2023-09-13 09:59 UTC, riverwanderer commented on vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
> +    // Reserved property VassalNextSide may override hotseat default; must be an available side
I intended the module to work with nextSide in english only.  Re-checking the code, the **sides** array is in english right, which would be ok ?

2023-09-13 10:05 UTC, riverwanderer commented on vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
> +    // Automated method: set VassalNextSide (may be a Global Option ie private or a Module Global Property)
I was referring to Global Option properties being local to the user. However, I'll remove that comment as I think I already removed the suggestion from the user doc update. I don't think it's helpful in the case of nextSide.

2023-09-14 12:13 UTC, riverwanderer commented on vassal-app/src/main/java/VASSAL/build/module/PlayerRoster.java
> +    // Reserved property VassalNextSide may override hotseat default; must be an available side
hmmm, yes looks like I do need to translate VassalNextSide, @Cattlesquat. I've done that in the latest PR. Will re-test.

2023-09-14 16:32 UTC, riverwanderer commented
Tested OK.  Using a modified version of Liberté - the end of turn "solo" procedure is able to correctly default to the next side, with english and when Definition of Sides is translated to French.

2023-09-14 16:49 UTC, riverwanderer commented
This PR doesn't create any v3.7 conflicts, can it be re-classified for the 3.7.1 milestone?

2023-09-20 14:35 UTC, riverwanderer commented
Merged and re-tested OK. Reference Manual update included. 

Note that this change should have no effect on modules unless the designer opts-in by defining the controlling global property VassalNextSide.

2023-09-21 12:22 UTC, riverwanderer commented
PR superseded by #12732.

2023-09-21 12:22 UTC, closed without merging