Null the decks sortListener on exit
vassalengine/vassal pull request #12907
Opened 2023-11-14 21:22 UTC by rlament

This fixes deck sorting not working on the next and each subsequent "File->New Game". The deck sort HotKey works the first instance of a game module. After a "File->Close" and then "New Game", the sort HotKey does not work. The workaround prior to this fix: user must completely exit Vassal and restart it.

The sortListener must be null to successfully assign a new HotKey during initialization.

2023-11-19 22:30 UTC, BrentEaston requested changes
Excellent pick-up, thanks very much for the PR.

Looks like the DeckSendKeyCommand has the same problem, can you update the PR to include that one as well? Thanks

2023-11-20 06:31 UTC, rlament commented
> Excellent pick-up, thanks very much for the PR.
> 
> Looks like the DeckSendKeyCommand has the same problem, can you update the PR to include that one as well? Thanks

In my module, the deck has both a DeckSendKeyCommand and a DeckSortKeyCommand. DeckSendKeyCommand has been working for me; don't see an issue there. DeckSendKeyCommand has similar code, but it doesn't seem to be used at all in the player, perhaps only in the editor? I set numerous breakpoints in DeckSendKeyCommand.java and didn't hit them from the player. It seems that DeckSendKeyCommand's are registered in some other way, but at this point I'm not sure where that is. At least it's not via `DeckSendKeyCommand.registerListeners()`.

At this point, I don't see the need to make any changes other than changing the title of this pull request to specifically say "Deck Sort Key Commands..."

2023-11-20 08:59 UTC, BrentEaston commented
My testing indicates the Deck Send Key Command is failing in exactly the same way, for the same reason, as the Deck Sort Key Command.

2023-11-20 15:44 UTC, rlament commented
@BrentEaston Sorry, my confusion with Deck Send Key Command and Deck Global Key Command. Testing with correct command (Send not Global), I can reproduce the failure. You are right, Deck Send Key Command requires the same fix.

2023-11-23 11:27 UTC, BrentEaston approved these changes
Looks good to me!

2023-11-23 22:05 UTC, uckelman commented
@rlament Thanks for the contribution. I'd like to add your name to our list of contributers if you're willing. How should I list you?

2023-11-23 22:05 UTC, merged

2023-11-25 16:35 UTC, rlament commented
> Thanks for the contribution. I'd like to add your name to our list of contributers if you're willing. How should I list you?

@uckelman Glad to see this fix going into the main branch without delay. I'd be happy to be listed as a contributor. List me as: Ray Lament

2023-11-25 17:39 UTC, uckelman commented
I've added you to the list. You'll show up [here](https://vassalengine.org/about.html#team) the next time I deploy the site.