13297 - Deselect - way to cause deselection and stack-removal for a specific piece.
vassalengine/vassal pull request #221
Opened 2020-08-18 19:04 UTC by Cattlesquat

![image](https://user-images.githubusercontent.com/3742246/90554474-ecdade00-e163-11ea-9893-fd8a914f9e95.png)

There have been requests for the ability to deselect pieces w/ a key command. This implements that in a nice little trait. Optionally the deselected piece can also be popped out of its stack (useful when what you're doing is "dropping a piece off" from a moving stack). 

Provides all the normal trait features, and I have provided localization hooks.

If approved I'll provide the documentation.

2020-08-31 20:04 UTC, uckelman requested changes

2020-08-31 20:44 UTC, Cattlesquat commented on vassal-app/src/main/java/VASSAL/counters/Deselect.java
> +    this(ID + Resources.getString("Deselect.Deselect") + ";K;;false", null);
That is actually the "default name" (localizable) of a default Deselect. The actual type is in ID I believe.

Mind you this thing was written before my most recent journeyman-course in Decent Sequence Encoder Separators.

2020-08-31 20:47 UTC, Cattlesquat commented on vassal-app/src/main/java/VASSAL/counters/Deselect.java
> +    this(ID + Resources.getString("Deselect.Deselect") + ";K;;false", null);
If we come up with some non-awful way to deal with "DELIMITER" in the Flare PR then I'd come fix this puppy right up.

2020-09-01 20:07 UTC, uckelman commented on vassal-app/src/main/java/VASSAL/counters/Deselect.java
> +    this(ID + Resources.getString("Deselect.Deselect") + ";K;;false", null);
So, some other traits do this:
```
this(ID + "Delete;D", null);
```
`Delete` is the default command name there. That's _not_ translated. Is there an example of another trait which is translated?

@BrentEaston Thoughts?

2020-09-01 22:00 UTC, Cattlesquat commented on vassal-app/src/main/java/VASSAL/counters/Deselect.java
> +  }
"Cannot resolve Constructor ArrayList(java.lang.String)"

2020-09-01 22:01 UTC, Cattlesquat commented
Realized they're not supposed to get translated "in the editor". So the hardcode form is correct.

2020-09-01 22:01 UTC, Cattlesquat commented on vassal-app/src/main/java/VASSAL/counters/Deselect.java
> +    this(ID + Resources.getString("Deselect.Deselect") + ";K;;false", null);
You are correct - fixed & pushed.

2020-09-01 22:07 UTC, BrentEaston commented
Yes, there is a method to translate menu commands when translating the module to another language.

However, I think your original point is valid, that if we are creating a new module using German as the base language,not English, then it is reasonable that the default Command names be supplied in German,

They can then be translated to English in the module if someone ones to make an English version.

This something I missed in my i18n guidelines. 

I am pretty sure there are other similar cases.

2020-09-01 22:30 UTC, uckelman commented on vassal-app/src/main/java/VASSAL/counters/Deselect.java
> +  }
There should be an `ArrayList<T>(T... args)` ctor. It's dumb that there's not. Never mind, the way you were doing it fine.

2020-09-01 23:07 UTC, uckelman approved these changes

2020-09-01 23:07 UTC, uckelman commented
That's probably best to tackle for all traits at once.

2020-09-01 23:07 UTC, merged