13355: changes to EnsureVisible method map.java
vassalengine/vassal pull request #235
Opened 2020-08-21 22:36 UTC by claudiociardelli

Modified method EnsureVisible. Chenged behaviour, instead of showing a rectangle with the moved piece on one of the edges, it will show a rectangle so that the piece moved is in the center.

In addition the centering on opponent move will be triggered by a unit that is already visible by the opponent but that moves "too close" to the border of the visible area. 
For the moment "Too close" is defined as a band around the edges of 5% of the height or width of the visible rectangle.

2020-08-28 20:14 UTC, claudiociardelli commented on vassal-app/src/main/java/VASSAL/build/module/Map.java
> +      if (p.x < r_norecenter.x) bTriggerRecenter = true;
Agreed, but leaving it in lines makes it more readable. I personally prefer that.

2020-08-28 20:16 UTC, claudiociardelli commented on vassal-app/src/main/java/VASSAL/build/module/Map.java
> +      final double no_recenter_pct = 0.9;
Thx for pointing that out. I Refactored all the variables

2020-08-28 20:42 UTC, Cattlesquat commented on vassal-app/src/main/java/VASSAL/build/module/Map.java
> +      final double no_recenter_pct = 0.9;
Cool. Be sure to "push" your new changes after you commit them on your local branch, so that they will appear here.

2020-08-29 16:57 UTC, uckelman requested changes

2020-08-29 16:57 UTC, uckelman commented on vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
> +    double sensitivity;
You don't need to turn this into a double yourself; you can just return the int and it will be upcast.

2020-08-29 16:57 UTC, uckelman commented on vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
> +    if (sensitivity < 0) {
Should be an `else if`.

2020-08-29 16:57 UTC, uckelman commented on vassal-app/src/main/java/VASSAL/build/module/GlobalOptions.java
> +    double sensitivity;
I think what you want here is:
```
int sensitivity = (Integer) GameModule.getGameModule().getPrefs().getValue(CENTER_ON_MOVE_SENSITIVITY);
```

2020-08-29 16:57 UTC, uckelman commented on vassal-app/src/main/java/VASSAL/build/module/Map.java
> +      final double noRecenterPct = (100 - GlobalOptions.getInstance().centerOnOpponentsMoveSensitivity()) / 100;
If you want floating point division, you need to ensure one of the operands is a floating point type, say by using `100.0` instead of `100`.

2020-08-29 16:57 UTC, uckelman commented on vassal-app/src/main/java/VASSAL/build/module/Map.java
> +
This unnecessarily evaluates conditions after you've already set `bTriggerRecenter` to true.

Better would be:
```
bTriggerRecenter = p.x < rNorecenter.x || p.x > (rNorecenter.x + rNorecenter.width) ||
                   p.y < rNorecenter.y || p.y > (rNorecenter.y + rNorecenter.height);
```

2020-08-29 16:57 UTC, uckelman commented on vassal-app/src/main/java/VASSAL/build/module/Map.java
> +      if (bTriggerRecenter == true) {
You never need to check booleans for equality. Just write `if (bTriggerRecenter) {`.

2020-08-31 18:32 UTC, uckelman approved these changes

2020-08-31 20:10 UTC, merged