13329: Don't create new GpID's for temporary pieceslots
vassalengine/vassal pull request #253
Opened 2020-08-27 23:16 UTC by BrentEaston

used for editing pieces.

2020-08-27 23:26 UTC, BrentEaston commented
Putting this one hold while I investigate more issues raised by Barbanera.

2020-08-28 22:08 UTC, BrentEaston commented
3 related fixes for issue 13329. Ready to go for 3.4.0

2020-08-31 19:27 UTC, uckelman requested changes

2020-08-31 19:27 UTC, uckelman commented on vassal-app/src/main/java/VASSAL/build/GpIdChecker.java
> +            maxId = iid;
Couldn't it be `>` instead of `>=`?

2020-08-31 21:50 UTC, BrentEaston commented on vassal-app/src/main/java/VASSAL/build/GpIdChecker.java
> +            maxId = iid;
Indeed. Fixed

2020-08-31 21:57 UTC, uckelman approved these changes

2020-08-31 21:58 UTC, merged