3.5 - Localization - lots-o-stuff
vassalengine/vassal pull request #370
Opened 2020-09-27 20:25 UTC by Cattlesquat

2020-09-27 23:30 UTC, BrentEaston requested changes
Couple of tiny things

2020-09-27 23:42 UTC, Cattlesquat commented on vassal-app/src/main/java/VASSAL/configure/FontConfigurer.java
> +      family.setSelectedItem(value == null ? "SansSerif" : ((Font) value).getFamily()); //NON-NLS
fixed

2020-09-27 23:42 UTC, Cattlesquat commented on vassal-app/src/main/java/VASSAL/i18n/LocaleConfigurer.java
> +  //FIXME needs an i18n strategy and preferably the display version should be [Any Country].
k - left it unlocalized for now tho

2020-09-28 00:14 UTC, BrentEaston approved these changes

2020-09-28 00:14 UTC, merged