3.5 - Some remaining loc cleanup
vassalengine/vassal pull request #516
Opened 2020-10-29 18:09 UTC by Cattlesquat

There were a few last files in VASSAL.counters that didn't have localization keys and //NON-NLS markers in them.

2020-10-29 20:27 UTC, BrentEaston requested changes
Thanks for picking these up Brian. I've asked for the changes just to keep consistency with the way I did the other traits.

2020-10-29 20:27 UTC, BrentEaston commented on vassal-app/src/main/java/VASSAL/counters/PlaySound.java
> +    return Resources.getString("Editor.PlaySound.component_type") + ((format.getFormat().length() == 0) ? "" : " - " + format.getFormat());
I made a new thing for this. Use

return buildDescription("Editor.PlaySound.trait_description", format.getFormat());

2020-10-29 20:27 UTC, BrentEaston commented on vassal-app/src/main/java/VASSAL/counters/PropertySheet.java
> +    this(ID + ";" + Resources.getString("Editor.PropertySheet.component_type") + ";P;;;;", null); //NON-NLS
Make this key Editor.PropertySheet.default_command rather than Editor.PropertySheet.component_type

2020-10-29 20:27 UTC, BrentEaston commented on vassal-app/src/main/java/VASSAL/counters/PropertySheet.java
> +    return Resources.getString("Editor.PropertySheet.component_type");
And make this one Editor.PropertySheet.trait_description

2020-10-29 20:27 UTC, BrentEaston commented on vassal-app/src/main/java/VASSAL/counters/PropertySheet.java
> +    descriptions[0] = Resources.getString("Editor.PropertySheet.component_type");
And this one Editor.PropertySheet.property_sheet_command

2020-10-29 20:27 UTC, BrentEaston commented on vassal-app/src/main/java/VASSAL/counters/PlaySound.java
> +    menuText = st.nextToken(Resources.getString("Editor.PlaySound.component_type"));
Use Resources.getString("Editor.PlaySound.default_command")

2020-10-29 20:27 UTC, BrentEaston commented on vassal-app/src/main/java/VASSAL/counters/PlaySound.java
> +    return getI18nData(menuText, Resources.getString("Editor.PlaySound.component_type"));
USe Resources.getString("Editor.PlaySound.play_sound_command")

2020-10-30 14:14 UTC, Cattlesquat commented
Okay I think I hit all these!

2020-10-30 22:27 UTC, BrentEaston approved these changes

2020-10-30 22:27 UTC, merged