disable Refresh in Player if gpid errors, delete orphan pieces when r…
vassalengine/vassal pull request #680
Opened 2021-02-07 16:08 UTC by claudiociardelli

…efreshing

2021-02-07 16:14 UTC, claudiociardelli commented
Bug 13993 is fixed by PR680. If someone wants to test, use the latest Pursuit of Glory module in the module pages

2021-02-07 20:44 UTC, BrentEaston reviewed
Hi Claudio,

Overall, looks good.

Don't worry about checking the gpid's up front and disabling the run button as I suggested in Discord, this works just fine. Just make sure all messages presented to the users via an i18n key. Looks like there are several instances that where already untranslated before you started. These where once Vassal logfile only message, but are now being presented to the user so now need a translation.

2021-02-07 20:44 UTC, BrentEaston commented on vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
> +        log("Unable to run Refresh, module was saved with older vassal version. Edit and save module with latest vassal version first. "); //$NON-NLS-1$
Needs i18n

2021-02-07 20:44 UTC, BrentEaston commented on vassal-app/src/main/java/VASSAL/build/module/GameRefresher.java
> +        log("Deleting " + piece.getName() + "(" + piece.getId() + ") from game"); //$NON-NLS-1$
Needs i18n of strings

2021-02-07 20:59 UTC, BrentEaston requested changes
...

2021-02-09 11:18 UTC, BrentEaston approved these changes

2021-02-09 11:18 UTC, merged