14057-Improve Piece Definer image display width
vassalengine/vassal pull request #731
Opened 2021-02-17 09:52 UTC by BrentEaston

2021-02-17 15:49 UTC, uckelman commented on vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
> +  public void refresh() {
Why change the visibility?

2021-02-17 15:49 UTC, uckelman commented on vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
> +  public void splitChanged() {
Why change the visibility?

2021-02-17 20:14 UTC, BrentEaston commented on vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
> +  public void refresh() {
Ah, That was for testing, fixing.

2021-02-18 20:49 UTC, uckelman requested changes

2021-02-18 20:49 UTC, uckelman commented on vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
> +      boolean s = slot.isValid();
Looks unused.

2021-02-18 21:25 UTC, BrentEaston commented on vassal-app/src/main/java/VASSAL/counters/PieceDefiner.java
> +      boolean s = slot.isValid();
Fixed

2021-02-18 23:07 UTC, uckelman approved these changes

2021-02-18 23:07 UTC, merged